Fix ClassDefNotFoundErrors in shutdown hook
Make sure CrossMojoState class is loaded when the mojo is instantiated.
Otherwise if the CrossMojoState class has not been referenced before
anything goes wrong, the shutdownhook will cause a NoClassDefFoundError.